### ISSUE TITLE
Degradation error - just noting in case you know...

### ISSUE THREAD

**Issue by JamesOwers** [JamesOwers/midi_degradation_toolkit#49]
Running ./make_dataset.py, got this error:

```
Making target data:   0%|                                                                                                                        | 5/22522 [00:00<1:17:36,  4.84it/s]
Traceback (most recent call last):
  File "./make_dataset.py", line 457, in <module>
    degraded = deg_fun(excerpt, **deg_fun_kwargs)
  File "/Users/kungfujam/git/midi_degradation_toolkit/mdtk/degradations.py", line 37, in seeded_func
    return func(*args, **kwargs)
  File "/Users/kungfujam/git/midi_degradation_toolkit/mdtk/degradations.py", line 980, in join_notes
    degraded.loc[nexts[-1]]['dur'] -
IndexError: list index out of range
```

By the sounds of things, nexts is empty prematurely or something.

**Comment by JamesOwers** [comment]
Hmm...errored again upon rerun, diff data

```
Cleaning csv data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22522/22522 [03:16<00:00, 114.60it/s]
Making target data:   0%|                                                                                                                         | 15/22522 [00:00<10:36, 35.35it/s]
Traceback (most recent call last):
  File "./make_dataset.py", line 457, in <module>
    degraded = deg_fun(excerpt, **deg_fun_kwargs)
  File "/Users/kungfujam/git/midi_degradation_toolkit/mdtk/degradations.py", line 37, in seeded_func
    return func(*args, **kwargs)
  File "/Users/kungfujam/git/midi_degradation_toolkit/mdtk/degradations.py", line 980, in join_notes
    degraded.loc[nexts[-1]]['dur'] -
IndexError: list index out of range
```

**Comment by apmcleod** [comment]
Yeah, it does sound like that... I haven't seen that before, let me see if I can find it.
